String="Krithik"
Boolean=True
Integer=24
Float=13.23
print(type(String))
print(type(Boolean))
print(type(Integer))
print(type(Float))
Float=int(Float)
print(type(Float))
Integer=str(Integer)
print(type(Integer))
